version: "3"


volumes: 
   db-data: 

services: 
    vote: 
      image: schoolofdevops/vote
      ports: 
        - 5000:80
      depends_on: 
        - redis

    redis: 
      image: redis:alpine

    
    worker: 
      image: dipmohap/worker
      depends_on: 
        - redis
 
    db: 
      image: postgres:9.4
      volumes:
        - "db-data:/var/lib/postgresql/data"
   
    results: 
      image: schoolofdevops/vote-result
      ports:
        - 5001:80
      depends_on: 
        - db
